config/routes.rb
Rails.application.routes.draw do

  resources :transactions, only: [:new, :create]

  resources :profiles, except: [:index, :destroy]
  resources :listings

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  
  root 'users#index'

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

resources :users, only: [:show, :edit, :update, :destroy]

get "/auth/:provider/callback" => "sessions#create_from_omniauth"

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base

     belongs_to :user

      def self.create_with_omniauth(auth_hash)
        create! do |auth|
          auth.provider = auth_hash["provider"]
          auth.uid = auth_hash["uid"]
          auth.token = auth_hash["credentials"]["token"]
        end
      end

      def update_token(auth_hash)
        self.token = auth_hash["credentials"]["token"]
        self.save
      end

    end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	# has_many :reservations, :dependent => :destroy
	mount_uploaders :pictures, PictureUploader
	# validates_presence_of :price
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	validates_uniqueness_of :user_id
	mount_uploader :dis_pic, ImageUploader
end

app/models/user.rb
require 'securerandom'

class User < ActiveRecord::Base
  include Clearance::User
  has_many :authentications, :dependent => :destroy
  has_many :listings
  has_one :profile
  has_many :reservations

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      # u.first_name = auth_hash["info"]["first_name"]
      u.password = SecureRandom.hex(3)
      # u.encrypted_password = [*('A'..'Z')].sample(8).join
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

	before_action :require_login, only: [:edit, :update, :destroy, :create, :new]

  def create
  	@listing = Listing.new(params.require(:listing).merge(user_id: current_user.id).permit(:name, :home_type, :room_type, :accomodates, :address, :city, :user_id))
  	if @listing.save
  		redirect_to @listing
  	else
  		render :new
  	end
  end

  def new
  	@listing = Listing.new
  end

  def show
  	@listing = Listing.find(params[:id])
  end

  def index
  	@listing = Listing.all
  end

  def update
  	@listing = Listing.find(params[:id])
  	# @listing.update(params.require(:listing).permit(:name, :home_type, :room_type, :accomodates, :address, :city, :user_id))
  	@listing.update(listing_params)
    if @listing.save
  		redirect_to @listing
  	else
  		render :edit
  	end
  end

  def edit
  	@listing = Listing.find(params[:id])
    redirect_to @listing if current_user != @listing.user
  end

  def destroy
  	@listing = Listing.find(params[:id])
    redirect to listings_path if current_user != @listing.user
  	@listing.destroy
  	redirect_to listings_path
  end
end

private

def listing_params
  params[:listing][:user_id] = current_user.id
  params.require(:listing).permit(:name, :home_type, :room_type, :accomodates, :address, :city, :price, :user_id, {pictures: []})
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        # format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        # format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        # format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        # format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :location, :contact, :dis_pic, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

      def create_from_omniauth
        auth_hash = request.env["omniauth.auth"]

        authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
        if authentication.user
          user = authentication.user 
          authentication.update_token(auth_hash)
          @next = root_url
          @notice = "Signed in!"
        else
          user = User.create_with_auth_and_hash(authentication,auth_hash)
          @next = edit_user_path(user)   
          @notice = "User created - confirm or edit details..."
        end
        sign_in(user)
        redirect_to @next, :notice => @notice
      end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

	
  def index
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

	before_action :authenticate_user!
	before_action :check_cart!
	belongs_to :reservation

  def new
  	gon.client_token = generate_client_token
  end

  def create
  	@result = Braintree::Transaction.sale(
  			  amount: current_user.cart_total_price,
  			  payment_method_nonce: params[:payment_method_nonce])
  	if @result.success?
  		current_user.purchase_cart_listings!
  		redirect_to root_url, notice: "Congratulations! Your transaction has been successful!"
  	else
  		flash[:alert] = "Something went wrong while processing your transaction. Please try again."
  		gon.client_token = generate_client_token
  		render :new
  	end
  end

  private

  def generate_client_token
  	Braintree::ClientToken.generate
  end

  def check_cart!
  	if current_user.get_cart_listings.blank?
  		redirect_to root_url, alert: "Please add some items in your cart before processing your transaction!"
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<%=link_to "Checkout", new_transaction_path, class: "button" unless current_user.get_cart_movies.blank?%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= include_gon %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'vendor/modernizr' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <title>PearBnB</title>
</head>

<style>
body {
  padding-top: 40px;
}
</style>


<body>
  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>

  <!--Navbar -->
  <nav class="navbar navbar-inverse navbar-fixed-top" id="my-navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <a href="/" class="navbar-brand">PearBnB</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <% if signed_in? && current_user.profile != nil %>
          <li><%= link_to "Profile", profile_path(current_user.profile) %></li>
        <% elsif signed_in? && current_user.profile == nil %>
          <li><%= link_to "Profile", new_profile_path %></li>
        <% end %>
          <li><a href="/listings">Our Listings</a></li>
      </ul>
      <% if signed_in? %>
        <%= link_to "Sign out", sign_out_path, method: :delete, class:"btn btn-warning navbar-btn navbar-right" %>
      <% else %>
        <%= link_to "Sign in", sign_in_path, class:"btn btn-warning navbar-btn navbar-right" %>
      <% end %>
        </div>
      </div>
    </nav>

  <div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
    <h2 class="mbs">New Transaction</h2>
    <%= form_tag transactions_path do%>
      <p>Please enter your payment details:</p>
      <div id="dropin"></div>
      <%=submit_tag "Pay #{current_user.cart_total_price}$", class: "button mt1" %>
    <%end%>
  </div>

<%= yield %>
<footer>
<div class="container text-center">
  <hr>
  <p>&copy; ZingzBa</p>
</div>
</footer>

  <script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :home_type %><br>
    <%= f.text_field :home_type %>
  </div>
    <div class="field">
    <%= f.label :room_type %><br>
    <%= f.text_field :room_type %>
  </div>
    <div class="field">
    <%= f.label :accomodates %><br>
    <%= f.text_field :accomodates %>
  </div>
    <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
    <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
<!--   <div class="field">
    <%# f.label :city %><br>
    <%# f.text_field :city %>
  </div> -->
  
    <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/destroy.html.erb
<h1>Listings#destroy</h1>
<p>Find me in app/views/listings/destroy.html.erb</p>

app/views/listings/edit.html.erb
<div class="container">
<br>
<h1>Edit Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %>
<%= link_to 'Back', listings_path %>
</div>

app/views/listings/index.html.erb
<h1>Listings#index</h1>
<p>Find me in app/views/listings/index.html.erb</p>

<div class='container'>

<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table width=151%>
  <thead>
    <tr>
      <th>Name</th>
      <th>Home Type</th>
      <th>Room Type</th>
      <th>Accomodates</th>
      <th>Address</th>
      <th>City</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr class="<%= cycle('list_line_odd','list_line_even') %>">
        <td><%= listing.name %></td>
        <td><%= listing.home_type %></td>
        <td><%= listing.room_type %></td>
        <td><%= listing.accomodates %></td>
        <td><%= listing.address %></td>
        <td><%= listing.city %></td>
        <td><%= listing.user.email %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>Listings#new</h1>
<p>Find me in app/views/listings/new.html.erb</p>

<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<h1>Listings#show</h1>
<p>Find me in app/views/listings/show.html.erb</p>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Home type:</strong>
  <%= @listing.home_type %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @listing.room_type %>
</p>

<p>
  <strong>Accommodates:</strong>
  <%= @listing.accommodates %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p>
  <strong>User:</strong>
  <%= @listing.user.email %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>

app/views/profiles/_form.html.erb
<div class="container">
  <%= form_for(@profile) do |f| %>
    <% if @profile.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
  
        <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%=f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :location %><br>
      <%=f.text_field :location %>
    </div>
    <div class="field">
      <%= f.label :contact %><br>
      <%=f.text_field :contact %>
    </div>
    <div class="field">
      <%= f.label :dis_pic %><br>
      <%=f.file_field :dis_pic %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<div class="container">
	<br>
	<%= render 'form' %>

	<%= link_to 'Show', @profile %> |
	<%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/index.html.erb
<div class='container'>
  <br>
  <p id="notice"><%= notice %></p>

  <table width="100%">
    <thead>
      <tr>
        <th>Name</th>
        <th>Location</th>
        <th>Contact</th>
        <th>Picture</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @profiles.each do |profile| %>
        <tr>
          <td><%= profile.name %></td>
          <td><%= profile.location %></td>
          <td><%= profile.contact %></td>
          <td><%= profile.picture %></td>
          <td><%= profile.user_id %></td>
          <td><%= link_to 'Show', profile %></td>
          <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
          <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Profile', new_profile_path %>
</div>

app/views/profiles/new.html.erb
<div class="container">
<br>
<%= render 'form' %>

<%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <br>
  <p id="notice"><%= notice %></p>

  <p>
    <%= image_tag @profile.dis_pic_url(:thumb).to_s, class:"img-circle" %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @profile.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @profile.location %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= @profile.contact %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @profile.user.email %>
  </p>

  <%= link_to 'Edit', edit_profile_path(@profile), class:"btn btn-warning" %> | <%= link_to 'Back', root_path, class:"btn btn-info" %>
</div>

app/views/transactions/new.html.erb
<h1>Transactions#new</h1>
<p>Find me in app/views/transactions/new.html.erb</p>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<a href="/auth/facebook">
<i class="fa fa-facebook"/>Log In with Facebook</a>

app/views/users/edit.html.erb
<h1>User Profile</h1>

app/views/users/index.html.erb
<h1>Welcome to PairBNB</h1>
<p>Rent a Place!</p> 
<p>Or Rent Your Place and Be a Host!</p>

<% if current_user.profile == nil %>
  <%= link_to "Let's Setup Your Profile", new_profile_path %>
 <% else %>
  <%= link_to "#{current_user.profile.name}'s profile", profile_path(current_user.profile.id) %>
<% end %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>User#show</h1>
<p>app/views/listings/show.html.erb</p>